### ISSUE TITLE
CPackDeb: Debian package requires a package version

### ISSUE THREAD

**Issue by MrAusnadian** [hyperledger/sawtooth-sdk-cxx#27]
When trying to build the SDK, I'm getting the following error:

```
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: sawtooth
CPack: - Install project: sawtooth
CPack: Create package
CMake Error at /usr/share/cmake-3.5/Modules/CPackDeb.cmake:577 (message):
  CPackDeb: Debian package requires a package version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CPackDeb.cmake:778 (cpack_deb_prepare_package_vars)
  


CPack Error: Error while execution CPackDeb.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: sawtooth-cxx-sdk
make: *** [package] Error 1
Makefile:94: recipe for target 'package' failed
```

Attempting to build using Github Actions: https://github.com/gluwa/sawtooth-sdk-cxx/actions

Workflow file is below:
```
name: C/C++ CI

on:
  push:
    branches: [ master, feature/build ]
  pull_request:
    branches: [ master, feature/build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        tags: sawtooth-sdk-cxx-local:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: sawtooth-sdk-cxx-local:latest
        options: -v ${{ github.workspace }}:/project/sawtooth-sdk-cxx
        run: build_cxx
```

**Comment by MrAusnadian** [comment]
Got it working with this updated action script:
```
name: Sawtooth SDK Cxx CI

on:
  push:
    branches: [ master, feature/build ]
  pull_request:
    branches: [ master, feature/build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        tags: sawtooth-sdk-cxx-local:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: sawtooth-sdk-cxx-local:latest
        options: -v ${{ github.workspace }}:/project/sawtooth-sdk-cxx
```
